config/routes.rb
Samegame::Application.routes.draw do
  resources :games, except: [:index, :edit, :delete] do
      post 'select_group', on: :member
      post 'update_game', on: :member
  end

  post 'restore_game' => 'games#restore_game', as: :restore_game

  root :to => 'games#new'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id         :integer          not null, primary key
#  user       :string(255)
#  width      :integer
#  height     :integer
#  colors     :integer
#  score      :integer
#  matrix     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Game < ActiveRecord::Base
  attr_accessible :colors, :height, :width, :user
  serialize :matrix

  extend FriendlyId
  friendly_id :user, use: :slugged

  validates :user, presence: true, :uniqueness => true
  validates :width, presence: true, :inclusion => { :in => 5..20, :message => "of the game field must be between 5 and 20"}, :numericality => { :only_integer => true }
  validates :height, presence: true, :inclusion => { :in => 5..20, :message => "of the game field must be between 5 and 20" }, :numericality => { :only_integer => true }
  validates :colors, presence: true, :inclusion => { :in => 3..10, :message => "used in game must be between 3 and 10" }, :numericality => { :only_integer => true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamePlay

  def index
    @games = Game.all
  end

  def show
    @game = Game.find_by_user(params[:id])
    @matrix = @game.matrix
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])
      if @game.save
        @game.update_attribute(:score, 0)
        matrix = generate_matrix @game
        @game.update_attribute(:matrix, matrix)
        redirect_to @game, notice: 'Lets Play'
      else
        render action: "new"
     end
  end

  def restore_game
      user = params[:user]
      @game = Game.find_by_user(user)
      if @game
          redirect_to @game, notice: "Game Restored"
      else
          redirect_to new_game_path , alert: "No user found"
      end
  end

def select_group
    id = params[:id]
    ball = params[:ball]
    matrix =  Game.find_by_user(id).matrix
    selected = find_group(ball, matrix)

    render :json => selected
  end

  def update_game
        id = params[:id]
        ball = params[:ball]
        game =  Game.find_by_user(id)
        matrix = game.matrix
        selected = find_group(ball, matrix)

        if selected
            deleted = update_matrix(selected)
            added = addBalls(game.colors)
            score = update_db(game, added)

            render :json => {selected: selected, deleted: deleted, added: added, score: score}
        else
            render :json => {selected: nil}
        end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for @game, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
<div id="fields">
  <p>
    <%= f.label :user %>
    <%= f.text_field :user, placeholder: "Please, enter your name" %>
  </p>
  <p>
    <%= f.label :width %>
    <%= f.number_field :width, placeholder: "game field width (5..20)" %>
  </p>
  <p>
    <%= f.label :height %>
    <%= f.number_field :height, placeholder: "game field height (5..20)" %>
  </p>
  <p>
    <%= f.label :colors %>
    <%= f.number_field :colors, placeholder: "game colors (3..10)" %>
  </p>
  <p>
    <%= f.submit "New Game", :class => 'btn btn-primary' %>
  </p>
</div>
<% end %>

app/views/games/_game_area.html.erb
<% balls = [asset_path('balls/blue.png'), asset_path('balls/green.png'), asset_path('balls/grey.png'), asset_path('balls/orange.png'), asset_path('balls/pink.png'), asset_path('balls/red.png'), asset_path('balls/yellow.png'), asset_path('balls/darkgreen.png'), asset_path( 'balls/darkblue.png'), asset_path('balls/lightgreen.png')]  %>
<%balls_s = [asset_path('balls/blue_s.png'), asset_path('balls/green_s.png'), asset_path('balls/grey_s.png'), asset_path('balls/orange_s.png'), asset_path('balls/pink_s.png'), asset_path('balls/red_s.png'), asset_path('balls/yellow_s.png'), asset_path('balls/darkgreen_s.png'), asset_path('balls/darkblue_s.png'), asset_path('balls/lightgreen_s.png')]  %>

<div id = "play_ground" data-colors = "<%= balls %>" data-colors_s = "<%=  balls_s%>" >
    <% for col in @matrix %>
          <ul>
              <% for color in col %>
                  <li>
                       <%= image_tag "#{balls[color]}", :alt => color %>
                  </li>
              <% end %>
          </ul>
    <% end %>
</div>

app/views/games/edit.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/games/index.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:width) %></th>
      <th><%= model_class.human_attribute_name(:height) %></th>
      <th><%= model_class.human_attribute_name(:colors) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:matrix) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.id, game_path(game) %></td>
        <td><%= game.user %></td>
        <td><%= game.width %></td>
        <td><%= game.height %></td>
        <td><%= game.colors %></td>
        <td><%= game.score %></td>
        <td><%= game.matrix %></td>
        <td><%=l game.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_game_path(game), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      game_path(game),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_game_path,
            :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<div class="page-header">
  <h3>This is a great Game, which help you to improve you brain and have fun.</h3>
  <h3>So, no more waiting, choose options and push New Game button below.</h3>
</div>

<%= render :partial => 'form' %>

app/views/games/show.html.erb
<div id = 'content'>
    <%=  render 'game_area' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samegame" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container">
        <div class="row">
          <div class="span9">
            <h1><%= link_to "Same Game", root_path %></h1>
            <% flash.each do |name, msg| %>
              <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">&#215;</a>
                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
              <% end %>
            <% end %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
                    <%= render "shared/sidebar" %>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Liubomyr Fedorniak 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_sidebar.html.erb
<% if params[:action] == "show"  %>
<h3>Game Info</h3>
<strong>Game field:</strong> <%= @game.width.to_s + " X " + @game.height.to_s %></br>
<strong>Colors: </strong><%= @game.colors %></br>
<strong>Score: </strong><b id = "score"><%= @game.score %></b></br>

<% else %>
    <h3>Restore Game</h3>
    You can restore your game, using your name:

    <%= form_tag restore_game_path, :html => { :class => 'form-horizontal' } do %>
        <p>
            <%= text_field_tag :user, nil, :class => 'text_field', placeholder: "User Name"  %>
        </p>
        <%= submit_tag "Restore Game", :class => 'btn btn-primary' %>
        <% end  %>
<% end  %>